<?php
/**
 * @file
 * Flip a switch to enable chromephp.php on your Drupal site.
 */

define('CHROMEPHP_PATH', drupal_get_path('module', 'chromephp'));

/**
 * Implements hook_permission().
 */
function chromephp_permission() {
  return array(
    'use chromephp' => array(
      'title' => t('Use ChromePhp'),
      'description' => t('Enables use of the chromephp.php library.'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function chromephp_init() {
  if (user_access('use chromephp')) {
    if (!class_exists('ChromePhp')) {
      $path = function_exists('libraries_get_path') ? libraries_get_path('ChromePhp') : 'sites/all/libraries/ChromePhp';
      if (!include($path . '/ChromePhp.php')) {
        $tokens = array('!path' => $path);
        $message = t('ChromePhp.php library was not found in !path. Please ensure the library exists in sites/all/libraries/ChromePhp.', $tokens);
        drupal_set_message($message);
      }
    }
  }
}

/**
 * Outputs a variable to console.
 */
function cpm($var = 'ChromePhp is working.') {
  return ChromePhp::log($var);
}

/**
 * Outputs a warning.
 */
function cpw($message = 'A warning.') {
  return ChromePhp::warn($message);
}

/**
 * Implements hook_menu().
 */
/*function chromephp_menu() {
  return array(

  );
}*/
